global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'jhipster'
rule_files:
  - "alerts.yml"
scrape_configs:
  - job_name: 'jhipster-app'
    scrape_interval: 5s
    metrics_path: /management/prometheus
    static_configs:
      - targets:
          - host.docker.internal:7070